titl = document.getElementById("titl")
titl.innerHTML = " ";
setTimeout(function(){titl.innerHTML = "M<span class=\"cur\">|</span>";}, 100)
setTimeout(function(){titl.innerHTML = "Mi<span class=\"cur\">|</span>";}, 250)
setTimeout(function(){titl.innerHTML = "Mik<span class=\"cur\">|</span>";}, 350)
setTimeout(function(){titl.innerHTML = "Mike<span class=\"cur\">|</span>";}, 450)
setTimeout(function(){titl.innerHTML = "Mike <span class=\"cur\">|</span>";}, 650)
setTimeout(function(){titl.innerHTML = "Mike V<span class=\"cur\">|</span>";}, 750)
setTimeout(function(){titl.innerHTML = "Mike Va<span class=\"cur\">|</span>";}, 900)
setTimeout(function(){titl.innerHTML = "Mike Vah<span class=\"cur\">|</span>";}, 1050)
setTimeout(function(){titl.innerHTML = "Mike Vahe<span class=\"cur\">|</span>";}, 1200)
setTimeout(function(){titl.innerHTML = "Mike Vahe <span class=\"cur\">|</span>";}, 1350)
setTimeout(function(){titl.innerHTML = "Mike Vahe M<span class=\"cur\">|</span>";}, 1550)
setTimeout(function(){titl.innerHTML = "Mike Vahe Mo<span class=\"cur\">|</span>";}, 1750)
setTimeout(function(){titl.innerHTML = "Mike Vahe Mou<span class=\"cur\">|</span>";}, 1900)
setTimeout(function(){titl.innerHTML = "Mike Vahe Moub<span class=\"cur\">|</span>";}, 2050)
setTimeout(function(){titl.innerHTML = "Mike Vahe Mouba<span class=\"cur\">|</span>";}, 2250)
setTimeout(function(){titl.innerHTML = "Mike Vahe Moubay<span class=\"cur\">|</span>";}, 2400)
setTimeout(function(){titl.innerHTML = "Mike Vahe Moubaye<span class=\"cur\">|</span>";}, 2550)
setTimeout(function(){titl.innerHTML = "Mike Vahe Moubayes<span class=\"cur\">|</span>";}, 2800)
setTimeout(function(){titl.innerHTML = "Mike Vahe Moubaye<span class=\"cur\">|</span>";}, 3600)
setTimeout(function(){titl.innerHTML = "Mike Vahe Moubayed<span class=\"cur\">|</span>";}, 3700)
